config/routes.rb
Rails.application.routes.draw do

  root :to => "polls#index"
  resources :polls
  post 'polls/vote/:id' => 'polls#vote', :as => :vote_poll

  resources :questions, path: "polls"

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  has_many :votes

  validates_presence_of :content
  validates :content, :length => {:minimum => 2}
end

app/models/message.rb
class Message < ActiveRecord::Base
  has_many :answer, class_name: "Message",
           foreign_key: "question_id",
           dependent: :destroy
  belongs_to :question, class_name: "Message"

  accepts_nested_attributes_for :question

end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers, :dependent => :destroy
  belongs_to :user

  accepts_nested_attributes_for :answers, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true

  validates :content, :length => {:minimum => 5}
  validate :answers_length_enough


  def answers_length_enough
    if self.answers.length < 2
      errors.add :answers, 'should be more than or equal 2'
    end
    if self.answers.select { |q| q._destroy == false }.length < 2
      errors.add :answers, 'cannot be less then 2'
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :questions, :dependent => :destroy
  has_many :votes, :dependent => :destroy

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :answer
  belongs_to :user

  validates_presence_of :answer, :answer_id
  validates_presence_of :user, :user_id

  validates_uniqueness_of :user_id, :scope => [:user_id, :answer_id]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :mark_user


  def mark_user
    cookies[:user_id] = current_user.uid if cookies[:user_id].nil?
  end

  def current_user
    @current_user = @current_user || save_user
  end


  def can_manage resource
    current_user.id == resource.user_id
  end

  helper_method :can_manage



  private

  def save_user
    uniq_id = cookies[:user_id] || generate_uniq_id
    User.find_or_create_by(
        :ip => request.remote_ip,
        :uid => uniq_id
    )
  end

  def generate_uniq_id
    (5...30).sort_by{rand}.join
  end

end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
  end

  def new
    @question = Question.new
    3.times do
      @question.answers.build
    end
  end

  def create
    @question = Question.new(poll_params)
    @question.user_id = current_user.id
    if @question.save
      flash[:notice] = "Successfully created"
      redirect_to polls_path
    else
      render :action => 'new'
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    check_access @question
    if @question.update_attributes(poll_params)
      flash[:notice] = "Successfully updated"
      redirect_to polls_path
    else
      render :action => 'edit'
    end
  end

  def destroy
    @question = Question.find(params[:id])
    check_access @question
    @question.destroy
    flash[:notice] = "Successfully destroyed"
    redirect_to polls_url
  end

  def vote
    vote = Vote.new ({
        :answer_id => params[:id],
        :user_id => current_user.id
    })
    vote.save


    flash[:notice] = "Thank you"
    redirect_to polls_url
  end

  private

  def check_access question
    throw "Permission error"  unless can_manage question
  end

  def poll_params
    params.require(:question).permit(:content, :answers_attributes => [:content, :_destroy, :id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/polls_helper.rb
module PollsHelper

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Poll</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if flash[:error] -%>
    <p class='error'><%=h flash[:error] %></p>
<% end -%>
<% if flash[:notice] -%>
    <p class='notice'><%=h flash[:notice] %></p>
<% end -%>

<%= yield %>

</body>
</html>

app/views/polls/_answer_fields.html.erb
<p class="answer-item">
  <%= f.label :content, "Answer" %>
  <%= f.text_field :content %>
  <%= f.check_box :_destroy %>
  <%= f.label :_destroy, "Remove" %>
</p>

app/views/polls/_form.html.erb
<%= form_for @question do |f| %>
    <% @question.errors.full_messages.each do |msg| %>
        <p><%= msg %></p>
    <% end %>

    <p>
      <%= f.label :content, "Question" %><br />
      <%= f.text_area :content, :cols => 40 %><br />
      <%= f.hidden_field :id %><br />
    </p>
    <div id="answers">
        <%= f.fields_for :answers do |builder| %>
            <%= render 'answer_fields', :f => builder %>
        <% end %>

      <div>
         <a id="add-new-answer" href="javascript: void(0)">Add new answer field</a>
      </div>
    </div>


  <p><%= f.submit "Submit" %></p>
<% end %>




<script id="answer-tmpl" type="text/template">

  <p class="answer-item">
    <label for="question_answers_attributes_**id**_content">Answer</label>
    <input id="question_answers_attributes_**id**_content" name="question[answers_attributes][**id**][content]" value="" type="text">
    <input name="question[answers_attributes][**id**][_destroy]" value="0" type="hidden">
  </p>

</script>

app/views/polls/edit.html.erb
<%= render :partial => 'form' %>

<p>
  <%= link_to "Show", poll_path(@question) %> |
  <%= link_to "View All", polls_path %>
</p>

app/views/polls/index.html.erb
<table>
  <% for question in @questions %>
    <tr>
      <td><%= question.content %></td>
      <td><%= link_to "Show", poll_path(question) %></td>
      <% if can_manage question %>
      <td><%= link_to "Edit", edit_poll_path(question) %></td>
      <td><%= link_to "Destroy",  poll_path(question), :confirm => 'Are you sure?', :method => :delete %></td>
      <% end %>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Poll", new_poll_path %></p>

app/views/polls/new.html.erb
<%= render :partial => 'form' %>

<p><%= link_to "Back to List", polls_path %></p>

app/views/polls/show.html.erb
<%=h @question.content %>
<h3>
  Answers
</h3>
<ul>
<% for answer in @question.answers %>
  <li>
    <%=h answer.content %>
    <%= link_to "Vote", vote_poll_path(answer),  :method => :post %>
    Votes: <%=h answer.votes.count %>
  </li>
<% end %>
</ul>

<p>
  <% if can_manage @question %>
    <%= link_to "Edit", edit_poll_path(@question) %> |
    <%= link_to "Destroy", poll_path(@question), :confirm => 'Are you sure?', :method => :delete %> |
  <% end %>
  <%= link_to "View All", polls_path %>
</p>